USE AdventureWorks2008R2
GO
CHECKPOINT 
GO
DBCC DROPCLEANBUFFERS;
GO


DBCC FREEPROCCACHE GO DBCC DROPCLEANBUFFERS GO DBCC FREESYSTEMCACHE ('ALL') GO DBCC FREESESSIONCACHE 

Read more: http://mrbool.com/how-to-clean-up-memory-sql-server/29242#ixzz3x7vRz91t